"""
Django settings for desklib project.

Generated by 'django-admin startproject' using Django 2.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from desklib.settings.base import *
# Application definition

INSTALLED_APPS += [
    'debug_toolbar',
]


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'desklib_dev_db',
        'USER': 'root',
        'PASSWORD': 'password',
    }
}

#Commented out in production envirment
SILENCED_SYSTEM_CHECKS = ['captcha.recaptcha_test_key_error']

EMAIL_HOST_USER = 'vishakha.sharma@locusrags.com'
EMAIL_HOST_PASSWORD = 'vishakhalocus7@4'

DEFAULT_FROM_EMAIL = 'vishakha.sharma@locusrags.com'

# DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440*4
# DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000*2
#https://sorl-thumbnail.readthedocs.io/en/latest/requirements.html kindly satisfy requirements for sorl-thumbnail.


THUMBNAIL_DEBUG = True
MIDDLEWARE += [
    'django.middleware.gzip.GZipMiddleware',
    'htmlmin.middleware.HtmlMinifyMiddleware',
    'htmlmin.middleware.MarkRequestMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',

]
HTML_MINIFY = True
KEEP_COMMENTS_ON_MINIFYING = False

# Paypal settings
PAYPAL_TEST = True
HAYSTACK_SEARCH_RESULTS_PER_PAGE = 6
META_USE_TITLE_TAG = True