# Generated by Django 2.2.2 on 2021-02-16 11:11

from django.db import migrations, models
import django.db.models.deletion
import tutors.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0016_subject_blog_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('profile_pic', models.ImageField(upload_to=tutors.models.img_uploads, verbose_name='profile_pic')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200, verbose_name='designation')),
                ('rating', models.IntegerField(verbose_name='rating')),
                ('review_content', models.TextField(verbose_name='review_content')),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('subjects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='subjects.Subject')),
            ],
        ),
    ]
