# Generated by Django 2.2.2 on 2021-02-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_auto_20210217_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50, verbose_name='skill')),
            ],
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='review_content',
        ),
        migrations.AddField(
            model_name='tutor',
            name='review_count',
            field=models.PositiveIntegerField(default=1, verbose_name='review_count'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='skills', to='tutors.Skills'),
        ),
    ]
