# Generated by Django 2.2.2 on 2019-07-11 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20190711_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='created',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='updated',
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
