# Generated by Django 2.2.2 on 2019-07-16 13:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20190711_1102'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0005_pageviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageViews',
            new_name='PageView',
        ),
    ]
