# Generated by Django 2.2.2 on 2019-08-01 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_auto_20190801_0749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='plan_days',
            new_name='days',
        ),
    ]
