# Generated by Django 2.2.2 on 2019-08-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_auto_20190806_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='slug',
                field=models.SlugField(unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
