# Generated by Django 2.2.2 on 2019-09-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_plan_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.IntegerField(default=9, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
