# Generated by Django 2.2.2 on 2019-09-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0011_sessionpageview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionpageview',
            name='session',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Session Id'),
        ),
    ]
