# Generated by Django 2.2.2 on 2019-09-02 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0011_plan_price'),
        ('subscription', '0012_auto_20190902_0604'),
    ]

    operations = [
    ]
