# Generated by Django 2.2.2 on 2019-12-03 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_document_redirect_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0013_merge_20190902_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_pay_per_download',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='documents',
            field=models.ManyToManyField(blank=True, null=True, to='documents.Document'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_pay_per_download',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.CreateModel(
            name='PayPerDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('expire_on', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documents', models.ManyToManyField(blank=True, null=True, to='documents.Document')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscription.Plan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pay_per_download', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
