# Generated by Django 2.2.2 on 2020-11-02 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0014_auto_20191203_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaypalInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_email', models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Buyer Email')),
                ('amount', models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Amount')),
                ('invoice_id', models.CharField(default=documents.utils.key_generator, editable=False, max_length=10, unique=True, verbose_name='Invoice Id')),
                ('status', models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Status')),
                ('currency', models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Status')),
                ('transaction_id', models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Transaction Id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paypal_invoice_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
