# Generated by Django 2.2.2 on 2019-12-18 12:21

import admissions.models
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AspirantDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('uk', 'United Kingdom'), ('australia', 'Australia')], max_length=70, verbose_name='Country')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Phone No')),
                ('qualification', models.CharField(choices=[('under_grad', 'Under Graduate'), ('graduate', 'Graduate'), ('post_graduate', 'Post Graduate'), ('doctorate', 'Doctorate')], max_length=30, verbose_name='Qualification')),
                ('stream', models.CharField(choices=[('arts', 'Arts'), ('science', 'Science'), ('tech', 'Technology'), ('commerce', 'Commerce')], max_length=30, verbose_name='Stream')),
                ('resume', models.FileField(max_length=1000, upload_to=admissions.models.upload_to, verbose_name='Upload Resume')),
                ('lokking_for_stream', models.CharField(choices=[('arts', 'Arts'), ('science', 'Science'), ('tech', 'Technology'), ('commerce', 'Commerce')], max_length=30, verbose_name='Looking For Stream')),
                ('lokking_for_course', models.CharField(choices=[('accounts', 'Accounting & Finance'), ('aeronautics', 'Aeronautical & Manufacturing Engineering'), ('agriculture', 'Agriculture & Forestry'), ('american', 'American Studies'), ('physiology', 'Anatomy & Physiology'), ('anthropology', 'Anthropology'), ('architecture', 'Architecture'), ('arts', 'Art & Design')], max_length=70, verbose_name='Looking for Course')),
                ('year', models.IntegerField(max_length=6, verbose_name='Session Year')),
            ],
        ),
    ]
