# Generated by Django 2.2.2 on 2019-12-27 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aspirantdetails',
            options={'verbose_name': 'Aspirant Detail', 'verbose_name_plural': 'Aspirant Details'},
        ),
    ]
