# Generated by Django 2.2.2 on 2020-04-13 07:10

import ckeditor_uploader.fields
from django.db import migrations, models
import meta.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('cover_page', models.ImageField(blank=True, null=True, upload_to='blog_cat/%Y/%m/%D')),
                ('seo_title', models.CharField(max_length=70, null=True)),
                ('seo_description', models.TextField(max_length=160, null=True)),
                ('seo_keywords', models.CharField(max_length=140, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Categories',
                'verbose_name': 'Blog Category',
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('short_description', models.TextField(blank=True, max_length=200, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('author', models.CharField(max_length=20, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(max_length=70, null=True)),
                ('seo_description', models.TextField(max_length=160, null=True)),
                ('seo_keywords', models.CharField(max_length=140, null=True)),
                ('category', models.ManyToManyField(blank=True, max_length=100, null=True, related_name='category_blog', to='blogs.BlogCategoryModel')),
            ],
            options={
                'verbose_name_plural': 'Blogs',
                'verbose_name': 'Blog',
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
    ]
