# Generated by Django 2.2.2 on 2019-09-23 09:47

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='college',
            field=models.CharField(default='', max_length=50, verbose_name='College'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='country',
            field=django_countries.fields.CountryField(default='IN', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='university',
            field=models.CharField(default='', max_length=50, verbose_name='University'),
            preserve_default=False,
        ),
    ]
