# Generated by Django 2.2.2 on 2019-10-07 09:35

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190923_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='contact_no',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+919876543210', max_length=20, region=None, verbose_name='contact number'),
        ),
    ]
