# Generated by Django 2.2.2 on 2019-10-16 04:30

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191007_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='contact_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None, verbose_name='contact number'),
        ),
    ]
