# Generated by Django 2.2.2 on 2020-10-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191016_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='university',
            field=models.CharField(max_length=500, verbose_name='University'),
        ),
    ]
