# Generated by Django 2.2.2 on 2019-06-14 10:21

from django.conf import settings
from django.db import migrations, models
import documents.models
import documents.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='first_sentence',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='First Sentence'),
        ),
        migrations.AlterField(
            model_name='document',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published Date'),
        ),
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=documents.utils.key_generator, editable=False, max_length=10, unique=True)),
                ('file', models.FileField(max_length=1000, upload_to=documents.models.all_files, verbose_name='File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', related_name='document_file', to='documents.Document')),
            ],
        ),
    ]
