# Generated by Django 2.2.2 on 2019-06-14 11:01

from django.conf import settings
from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0002_auto_20190614_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='document',
            name='main_file',
            field=models.FileField(default='a', max_length=1000, upload_to=documents.models.main_files, verbose_name=' Main File'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='page',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total pages'),
        ),
        migrations.AddField(
            model_name='document',
            name='pdf_converted_file',
            field=models.FileField(default='a', max_length=1000, upload_to=documents.models.pdf_converted_files, verbose_name=' Pdf converted file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='upload_file',
            field=models.FileField(default='a', max_length=1000, upload_to=documents.models.upload_to, verbose_name='Upload File'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='words',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Words'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(max_length=1000, upload_to=documents.models.images, verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', related_name='document_image', to='documents.Document')),
            ],
        ),
    ]
