# Generated by Django 2.2.2 on 2019-06-27 07:54

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0002_auto_20190622_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveIntegerField()),
                ('image_file', models.ImageField(max_length=1000, upload_to=documents.models.images, verbose_name='Image')),
                ('html', ckeditor.fields.RichTextField(verbose_name='Page html')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', related_name='document_image', to='documents.Document')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
