# Generated by Django 2.2.2 on 2019-06-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20190614_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='file',
            new_name='image_file',
        ),
    ]
