# Generated by Django 2.2.2 on 2019-06-17 06:40

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20190614_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='main_file',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=documents.models.main_files, verbose_name=' Main File'),
        ),
        migrations.AlterField(
            model_name='document',
            name='pdf_converted_file',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=documents.models.pdf_converted_files, verbose_name=' Pdf converted file'),
        ),
    ]
