# Generated by Django 2.2.2 on 2019-07-11 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20190704_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Is Published'),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Is Visible'),
        ),
        migrations.AlterField(
            model_name='document',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published Date'),
        ),
    ]
