# Generated by Django 2.2.2 on 2019-06-17 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20190617_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete='PROTECT', related_name='author_document', to=settings.AUTH_USER_MODEL),
        ),
    ]
