# Generated by Django 2.2.2 on 2019-07-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20190711_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='google_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='preview_from',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='document',
            name='preview_to',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='document',
            name='search_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='total_downloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
