# Generated by Django 2.2.2 on 2019-06-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20190617_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Title'),
        ),
    ]
