# Generated by Django 2.2.2 on 2019-06-21 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20190621_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='document',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
