# Generated by Django 2.2.2 on 2019-08-12 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0007_document_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='document',
            name='not_heplful',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Not Helpful'),
        ),
        migrations.AddField(
            model_name='document',
            name='was_heplful',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Helpful'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_issue', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Other Issues')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='documents.Document')),
                ('issue', models.ManyToManyField(blank=True, null=True, related_name='issue', to='documents.Issue')),
            ],
        ),
    ]
