# Generated by Django 2.2.2 on 2019-08-06 09:56

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Dimensions Should be 80x112 as per document ration', max_length=1000, null=True, upload_to=documents.models.cover_images, verbose_name='Image'),
        ),
    ]
