# Generated by Django 2.2.2 on 2019-08-09 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20190807_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='cover_image',
        ),
    ]
