# Generated by Django 2.2.2 on 2019-08-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20190807_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='not_heplful',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Not Helpful'),
        ),
        migrations.AlterField(
            model_name='document',
            name='was_heplful',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Helpful'),
        ),
        migrations.AlterField(
            model_name='report',
            name='other_issue',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Other Issues'),
        ),
    ]
