# Generated by Django 2.2.2 on 2019-08-14 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20190812_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='not_heplful',
            new_name='not_helpful',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='was_heplful',
            new_name='was_helpful',
        ),
    ]
