# Generated by Django 2.2.2 on 2019-09-06 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20190814_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='pdf_converted_file',
        ),
    ]
