# Generated by Django 2.2.2 on 2019-09-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_remove_document_pdf_converted_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='require_recalculation',
            field=models.BooleanField(default=True, verbose_name='Require Recalculation'),
        ),
    ]
