# Generated by Django 2.2.2 on 2019-09-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_document_require_recalculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cover_page_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Cover Page No.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='require_recalculation',
            field=models.BooleanField(default=False, verbose_name='Require Recalculation'),
        ),
    ]
