# Generated by Django 2.2.2 on 2019-09-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_auto_20190911_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='cover_page_number',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Cover Page No.'),
        ),
    ]
