# Generated by Django 2.2.2 on 2019-11-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_auto_20190913_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
    ]
