# Generated by Django 2.2.2 on 2019-11-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_document_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='canonical_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
