# Generated by Django 2.2.2 on 2019-11-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_document_canonical_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='redirect_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
