# Generated by Django 2.2.2 on 2020-01-15 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_auto_20200111_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='team',
            new_name='term',
        ),
    ]
