# Generated by Django 2.2.2 on 2020-01-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_auto_20200115_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Recommended max.length of relevant seo keyword is 140 characters', max_length=140, null=True),
        ),
    ]
