# Generated by Django 2.2.2 on 2020-06-23 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_auto_20200212_0722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': [('change_document_author', 'Staff Can Assign Document Author'), ('document_download_from_admin', 'Document Download From Admin')]},
        ),
    ]
