# Generated by Django 2.2.2 on 2020-06-24 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_auto_20200623_1002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': [('change_document_author', 'Staff Can Assign Document Author'), ('document_download_from_admin', 'Document Download From Admin')], 'verbose_name': 'document', 'verbose_name_plural': 'documents'},
        ),
    ]
