# Generated by Django 2.2.2 on 2020-09-30 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_auto_20200624_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': [('change_document_author', 'Staff Can Assign Document Author'), ('document_download_from_admin', 'Document Download From Admin'), ('search_in_description', 'Search in Description')], 'verbose_name': 'document', 'verbose_name_plural': 'documents'},
        ),
    ]
