# Generated by Django 2.2.2 on 2020-12-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0025_auto_20200930_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='total_downloads_to_show',
            field=models.PositiveIntegerField(default=0, verbose_name='Total downloads (to show on website)'),
        ),
        migrations.AddField(
            model_name='document',
            name='views_to_show',
            field=models.PositiveIntegerField(default=0, verbose_name='Views (to show on website)'),
        ),
        migrations.AddField(
            model_name='document',
            name='fake_reviews',
            field=models.PositiveIntegerField(default=0, verbose_name='Fake Reviews'),
        ),
        migrations.AlterField(
            model_name='document',
            name='total_downloads',
            field=models.PositiveIntegerField(default=0, verbose_name='Total downloads (actual)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Views (actual)'),
        ),
    ]
