# Generated by Django 2.2.2 on 2020-12-17 05:57

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0026_auto_20201217_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='total_downloads_to_show',
            field=models.PositiveIntegerField(default=documents.models.randomNumberDownloads, verbose_name='Total downloads (to show on website)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='views_to_show',
            field=models.PositiveIntegerField(default=documents.models.randomNumberViews, verbose_name='Views (to show on website)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='fake_reviews',
            field=models.PositiveIntegerField(default=documents.models.randomNumberRating, verbose_name='Fake Reviews'),
        ),
    ]
