# Generated by Django 2.2.2 on 2020-12-28 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0028_remove_document_total_downloads_to_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='fake_reviews',
        ),
        migrations.RemoveField(
            model_name='document',
            name='views_to_show',
        ),
    ]
