# Generated by Django 2.2.2 on 2021-01-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0029_auto_20201228_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': [('change_document_author', 'Staff Can Assign Document Author'), ('document_download_from_admin', 'Document Download From Admin'), ('search_in_description', 'Search in Description'), ('can_view_all_fields', 'Can View All Fields')], 'verbose_name': 'document', 'verbose_name_plural': 'documents'},
        ),
    ]
