# Generated by Django 2.2.2 on 2019-11-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='description',
        ),
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(default='dssdsd', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='jhghjb', max_length=200),
            preserve_default=False,
        ),
    ]
