# Generated by Django 2.2.2 on 2019-11-20 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_review_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
    ]
