# Generated by Django 2.2.2 on 2019-11-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_remove_review_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
