# Generated by Django 2.2.2 on 2019-07-03 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0002_auto_20190627_1154'),
        ('user_sessions', '0002_auto_20190627_0754'),
    ]

    operations = [
    ]
