# Generated by Django 2.2.2 on 2019-06-11 11:28
import json

from django.db import migrations


def add_subjects_data(apps, schema_editor):
    filename = 'subjects/data/subjects.json'  # https://github.com/classcentral/online-course-taxonomy
    with open(filename, 'r') as f:
        subjects_data = json.load(f)

    for subject, data in subjects_data.items():
        Subject = apps.get_model("subjects", "Subject")
        slug = data.get("slug")
        keywords = data.get("keywords")
        subject_obj = Subject()
        subject_obj.name = subject
        subject_obj.slug = slug
        subject_obj.save()
        subject_obj.keywords.add(keywords)


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_subjects_data),
    ]
