# Generated by Django 2.2.2 on 2019-11-13 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import subjects.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0003_auto_20190812_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='author',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Search Engine like max. 2048 characters of url', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, help_text='Image of the subject', null=True, upload_to=subjects.models.get_file_path),
        ),
        migrations.AddField(
            model_name='subject',
            name='image_alt_text',
            field=models.CharField(blank=True, help_text='Alternate text of subject image', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='info_graphic_image',
            field=models.ImageField(blank=True, help_text='Graphic image of the parent subject', null=True, upload_to=subjects.models.get_file_path),
        ),
        migrations.AddField(
            model_name='subject',
            name='info_graphic_image_alt_text',
            field=models.CharField(blank=True, help_text='Alternate text of parent subject graphic image', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='introduction',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Introduction'),
        ),
        migrations.AddField(
            model_name='subject',
            name='last_edited',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_last_edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Tip: Create concise and high-quality descriptions that accurately describe your page, Make sure each page on our website has a different description.', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Recommended max.length of relevant seo keyword is 140 characters', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Tip: Start every main word in the title with a capital letter, Keep title brief and descriptive that is relevant to the content of your pages.', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='subject',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sub heading'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
    ]
