# Generated by Django 2.2.2 on 2019-11-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_auto_20191113_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
