# Generated by Django 2.2.2 on 2019-11-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_subject_is_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='introduction',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='short_description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Short description'),
        ),
    ]
