# Generated by Django 2.2.2 on 2019-11-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_auto_20191126_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Tip: Create concise and high-quality descriptions that accurately describe your page, Make sure each page on our website has a different description.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Recommended max.length of relevant seo keyword is 140 characters', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Tip: Start every main word in the title with a capital letter, Keep title brief and descriptive that is relevant to the content of your pages.', max_length=150, null=True),
        ),
    ]
