# Generated by Django 2.2.2 on 2020-03-23 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_subjectcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcontent',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_content', to='subjects.Subject'),
        ),
    ]
