# Generated by Django 2.2.2 on 2020-06-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0011_auto_20200330_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectcontent',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
