# Generated by Django 2.2.2 on 2020-06-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0012_subjectcontent_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectcontent',
            name='short_description',
        ),
        migrations.AddField(
            model_name='subject',
            name='study_short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
