# Generated by Django 2.2.2 on 2020-09-09 05:49

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0014_subject_parent_question_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectQuestionContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_question_content', to='subjects.Subject')),
            ],
            options={
                'verbose_name': 'subject question content',
                'verbose_name_plural': 'subject question content',
            },
        ),
    ]
