# Generated by Django 2.2.2 on 2020-10-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0015_subjectquestioncontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='blog_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Blog Title'),
        ),
    ]
