# Generated by Django 2.2.2 on 2020-02-26 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import homework_help.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0008_auto_20191126_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('upload_file', models.FileField(max_length=1000, upload_to=homework_help.models.upload_to, verbose_name='Upload File')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Is Visible')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='author_question', to=settings.AUTH_USER_MODEL)),
                ('subjects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_question', to='subjects.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Unassigned'), (2, 'In Progress'), (3, 'Completed'), (4, 'Delivered'), (5, 'Feedback'), (6, 'Cancelled')], db_index=True, default=1)),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Question')),
                ('budget', models.IntegerField(blank=True, null=True, verbose_name='Budget')),
                ('amount_paid', models.IntegerField(blank=True, null=True, verbose_name='Amount Paid')),
                ('order_id', models.CharField(default=homework_help.models.key_generator, editable=False, max_length=10, unique=True)),
                ('uuid', models.CharField(default=homework_help.models.key_generator, editable=False, max_length=10, unique=True)),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Is Accepted')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Published')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordered_question', to='homework_help.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
