# Generated by Django 2.2.2 on 2020-02-28 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import homework_help.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homework_help', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField(verbose_name='Solution')),
                ('solution_files', models.FileField(max_length=1000, upload_to=homework_help.models.upload_solutions, verbose_name='Upload File')),
                ('answer_id', models.CharField(default=homework_help.models.key_generator, editable=False, max_length=10, unique=True)),
                ('is_concise', models.BooleanField(default=False, verbose_name='Is Concise')),
                ('is_detailed', models.BooleanField(default=False, verbose_name='Is Detailed')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Is Visible')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='author_answer', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_question', to='homework_help.Question')),
            ],
        ),
    ]
