# Generated by Django 2.2.2 on 2020-03-04 07:42

import django.core.validators
from django.db import migrations, models
import homework_help.models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_help', '0002_auto_20200228_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reference_files',
            field=models.FileField(blank=True, null=True, upload_to=homework_help.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif'])], verbose_name='Reference File'),
        ),
    ]
