# Generated by Django 2.2.2 on 2020-03-02 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_help', '0002_auto_20200228_0620'),
        ('homework_help', '0002_auto_20200228_0408'),
    ]

    operations = [
    ]
