# Generated by Django 2.2.2 on 2020-03-02 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_help', '0003_merge_20200302_0544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
    ]
