# Generated by Django 2.2.2 on 2020-03-05 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_help', '0003_merge_20200302_0544'),
        ('homework_help', '0003_auto_20200304_0742'),
    ]

    operations = [
    ]
