# Generated by Django 2.2.2 on 2020-03-11 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework_help', '0005_auto_20200306_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionfile',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_questionfiles', to='homework_help.Question'),
        ),
    ]
