# Generated by Django 2.2.2 on 2020-03-11 09:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homework_help', '0006_auto_20200311_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionfile',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
