# Generated by Django 2.2.2 on 2020-03-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_help', '0007_questionfile_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionfile',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='questionfile',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
