# Generated by Django 2.2.2 on 2020-03-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_help', '0009_auto_20200316_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_detailed',
            field=models.BooleanField(default=False, verbose_name='Is Detailed'),
        ),
    ]
