# Generated by Django 2.2.2 on 2020-03-26 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_help', '0010_order_is_detailed'),
        ('homework_help', '0004_auto_20200302_1404'),
    ]

    operations = [
    ]
