# Generated by Django 2.2.2 on 2020-03-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_help', '0010_order_is_detailed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Question Recieved'), (2, 'Payment Completed'), (3, 'Expert Working on your Answer'), (4, 'Answer is posted')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
