# Generated by Django 2.2.2 on 2020-03-26 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_help', '0011_merge_20200326_0546'),
        ('homework_help', '0011_auto_20200325_0652'),
    ]

    operations = [
    ]
