# Generated by Django 2.2.2 on 2020-04-09 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework_help', '0012_merge_20200326_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='author_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
