# Generated by Django 2.2.2 on 2020-04-20 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import homework_help.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homework_help', '0014_auto_20200409_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.TextField(blank=True, max_length=500, null=True, verbose_name='title')),
                ('file', models.FileField(max_length=1000, upload_to=homework_help.models.upload_question_to, verbose_name='Answer File')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answerfiles', to='homework_help.Answers')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
