# Generated by Django 2.2.2 on 2020-04-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_help', '0014_auto_20200409_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionfile',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='content'),
        ),
    ]
