# Generated by Django 2.2.2 on 2020-04-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_help', '0016_auto_20200420_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='solution_files',
        ),
    ]
