# Generated by Django 2.2.2 on 2020-04-20 12:06

from django.db import migrations, models
import homework_help.models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_help', '0017_remove_answers_solution_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerfile',
            name='file',
            field=models.FileField(max_length=1000, upload_to=homework_help.models.upload_answer_to, verbose_name='Answer File'),
        ),
    ]
