# Generated by Django 2.2.2 on 2020-04-23 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_help', '0015_questionfile_content'),
        ('homework_help', '0018_auto_20200420_1206'),
    ]

    operations = [
    ]
