# Generated by Django 2.2.2 on 2020-04-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_help', '0019_merge_20200423_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='seo_description',
            field=models.TextField(default='fdsfsdfsdf', help_text='Tip: Create concise and high-quality descriptions that accurately describe your page, Make sure each page on our website has a different description.', max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Recommended max.length of relevant seo keyword is 140 characters', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='seo_title',
            field=models.CharField(default='sfdfsgd gf gdf', help_text='Tip: Start every main word in the title with a capital letter, Keep title brief and descriptive that is relevant to the content of your pages.', max_length=90),
            preserve_default=False,
        ),
    ]
