# Generated by Django 2.2.2 on 2020-04-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_help', '0022_auto_20200427_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionfile',
            name='require_recalculation',
            field=models.BooleanField(default=False, verbose_name='Require Recalculation'),
        ),
    ]
