# Generated by Django 2.2.2 on 2020-04-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_help', '0023_questionfile_require_recalculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount_paid',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Amount Paid'),
        ),
    ]
