# Generated by Django 2.2.2 on 2020-04-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_help', '0024_auto_20200427_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Question Recieved'), (2, 'Payment Updated'), (3, 'Expert Working on your Answer'), (4, 'Answer is posted')], db_index=True, default=1),
        ),
    ]
