# Generated by Django 2.2.2 on 2020-04-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_help', '0025_auto_20200428_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionfile',
            name='title',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='title'),
        ),
    ]
