# Generated by Django 2.2.2 on 2020-05-04 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homework_help', '0026_auto_20200429_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published Date'),
        ),
    ]
