# Generated by Django 2.2.2 on 2020-07-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_help', '0028_auto_20200519_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_timezone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Client TimeZone'),
        ),
        migrations.AddField(
            model_name='order',
            name='deadline_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deadline Time'),
        ),
        migrations.AddField(
            model_name='order',
            name='expected_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='Expected Time'),
        ),
    ]
