# Generated by Django 2.2.2 on 2020-10-26 10:16

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_help', '0029_auto_20200714_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_publicly_visible',
            field=models.BooleanField(default=False, verbose_name='Publicly Visible'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='solution',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Solution'),
        ),
    ]
