# Generated by Django 2.2.2 on 2020-11-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_help', '0030_auto_20201026_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkAccordion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accordion_title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('accordion_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_visible', models.BooleanField(default=False, verbose_name='Is Visible')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='solution_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
