# Generated by Django 2.2.2 on 2021-03-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_help', '0031_auto_20201105_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkaccordion',
            name='is_faq',
            field=models.BooleanField(default=False, verbose_name='Is FAQ'),
        ),
        migrations.AlterModelOptions(
            name='homeworkaccordion',
            options={'verbose_name': 'Homework/Faq accordion', 'verbose_name_plural': 'Homework/Faq accordions'},
        ),
    ]
