# Generated by Django 2.2.2 on 2021-03-18 05:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_help', '0032_homeworkaccordion_is_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkaccordion',
            name='accordion_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
