# Generated by Django 2.2.2 on 2019-08-02 07:13

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import samples.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('type', models.IntegerField(choices=[(1, 'Resume')], db_index=True, default=1)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('upload_sample', models.FileField(max_length=1000, upload_to=samples.models.upload_to, verbose_name='Upload Sample')),
                ('total_downloads', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('search_clicks', models.PositiveIntegerField(default=0)),
                ('google_clicks', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Is Visible')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published Date')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField()),
                ('seo_title', models.CharField(help_text='Tip: Start every main word in the title with a capital letter, Keep title brief and descriptive that is relevant to the content of your pages.', max_length=70)),
                ('seo_description', models.TextField(help_text='Tip: Create concise and high-quality descriptions that accurately describe your page, Make sure each page on our website has a different description.', max_length=160)),
                ('seo_keywords', models.CharField(help_text='Recommended max.length of relevant seo keyword is 140 characters', max_length=140)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='author_samples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sample',
                'verbose_name_plural': 'samples',
            },
        ),
    ]
