# Generated by Django 2.2.2 on 2019-08-02 10:15

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_auto_20190802_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='pdf_converted_file',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=documents.models.pdf_converted_files, verbose_name=' Pdf converted file'),
        ),
    ]
