# Generated by Django 2.2.2 on 2019-09-02 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='author_samples', to=settings.AUTH_USER_MODEL),
        ),
    ]
