# Generated by Django 2.2.2 on 2019-10-01 10:27

from django.db import migrations, models
import django_countries.fields
import uploads.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0003_auto_20190812_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(db_index=True, max_length=200, verbose_name='Course Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('course_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Course Code')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('university', models.CharField(blank=True, max_length=50, null=True, verbose_name='University / College')),
                ('type', models.IntegerField(choices=[(1, 'Notes'), (2, 'Study Material'), (3, 'Assignment Brief'), (4, 'Book'), (5, 'Journal'), (6, 'Solution'), (7, 'Presentation'), (8, 'Thesis'), (9, 'Research Paper')], db_index=True, default=6)),
                ('upload_file', models.FileField(max_length=1000, upload_to=uploads.models.upload_to, verbose_name=' Upload File')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is visible')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('subjects', models.ManyToManyField(db_index=True, related_name='subject_uploads', to='subjects.Subject')),
            ],
            options={
                'verbose_name': 'upload',
                'verbose_name_plural': 'uploads',
            },
        ),
    ]
