# Generated by Django 2.2.2 on 2019-10-01 11:44

import django.core.validators
from django.db import migrations, models
import uploads.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_auto_20191001_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='upload_file',
            field=models.FileField(max_length=1000, upload_to=uploads.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name=' Upload File'),
        ),
    ]
