# Generated by Django 2.2.2 on 2019-10-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_auto_20191001_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Accepted'), (7, 'Rejected')], default=1, null=True),
        ),
    ]
