# Generated by Django 2.2.2 on 2020-05-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0007_remove_upload_required_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='unique_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
