# Generated by Django 2.2.2 on 2020-05-20 11:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0008_upload_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='unique_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
