# Generated by Django 2.2.2 on 2020-05-20 11:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0009_auto_20200520_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfordocument',
            name='unique_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
