# Generated by Django 2.2.2 on 2020-05-20 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0010_uploadfordocument_unique_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfordocument',
            old_name='unique_id',
            new_name='uid',
        ),
    ]
