# Generated by Django 2.2.2 on 2020-05-28 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0011_auto_20200520_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfordocument',
            options={'verbose_name': 'upload', 'verbose_name_plural': 'uploads'},
        ),
    ]
