# Generated by Django 2.2.2 on 2020-05-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0012_auto_20200528_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfordocument',
            options={'verbose_name': 'upload for document', 'verbose_name_plural': 'uploads for document'},
        ),
    ]
