# Generated by Django 2.2.2 on 2020-10-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0014_uploadfordocument_is_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='university',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='University / College'),
        ),
    ]
